/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas_iniciais;

import classes.Usuario;
import janela_estatisticas.JanelaDeEstatisticas;
import janela_estatisticas.JanelaDeEstatisticasContasReceber;
import janela_gerenciar_contas.JanelaPrincipal;
import janela_gerenciar_usuarios.JanelaPrincipalUsuarios;
import janela_gerenciar_clientes.JanelaPrincipalClientes;
import janela_pesquisar.JanelaPesquisarPrincipal;
import java.awt.event.ActionEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;

/**
 *
 * @author bruno
 */
public class MenuPrincipal extends javax.swing.JFrame {
private Usuario usuario;
private DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
private Date date = new Date();
    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }
    
    public MenuPrincipal(Usuario user) {
        initComponents();
        this.usuario = user;
        this.lblDataHora.setText( dateFormat.format( date )  );
        
        if(this.usuario.getNivel_acesso() <= 2){
            this.btnGerenciarUsuarios.setEnabled(false);
        }
        if(this.usuario.getNivel_acesso() <= 1){
            this.btnGerenciarClientes.setEnabled(false);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnEstatisticas = new javax.swing.JButton();
        btnGerenciarContas = new javax.swing.JButton();
        btnGerenciarClientes = new javax.swing.JButton();
        btnGerenciarUsuarios = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        lblDataHora = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sair");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(530, 10, 30, 20);

        btnEstatisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/finances.png"))); // NOI18N
        btnEstatisticas.setText("Gráficos e Relatórios");
        btnEstatisticas.setIconTextGap(10);
        btnEstatisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEstatisticasMouseClicked(evt);
            }
        });
        btnEstatisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstatisticasActionPerformed(evt);
            }
        });
        getContentPane().add(btnEstatisticas);
        btnEstatisticas.setBounds(49, 110, 490, 60);

        btnGerenciarContas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/check.png"))); // NOI18N
        btnGerenciarContas.setText("Gerenciar Contas");
        btnGerenciarContas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGerenciarContas.setIconTextGap(10);
        btnGerenciarContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciarContasActionPerformed(evt);
            }
        });
        getContentPane().add(btnGerenciarContas);
        btnGerenciarContas.setBounds(50, 270, 205, 60);

        btnGerenciarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/deal.png"))); // NOI18N
        btnGerenciarClientes.setText("Gerenciar Clientes");
        btnGerenciarClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGerenciarClientes.setIconTextGap(10);
        btnGerenciarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciarClientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnGerenciarClientes);
        btnGerenciarClientes.setBounds(320, 270, 220, 60);

        btnGerenciarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/user.png"))); // NOI18N
        btnGerenciarUsuarios.setText("Gerenciar Usuários");
        btnGerenciarUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGerenciarUsuarios.setIconTextGap(10);
        btnGerenciarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciarUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnGerenciarUsuarios);
        btnGerenciarUsuarios.setBounds(320, 190, 220, 60);

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/search.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPesquisar.setIconTextGap(10);
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar);
        btnPesquisar.setBounds(50, 190, 205, 60);

        lblDataHora.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDataHora.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblDataHora);
        lblDataHora.setBounds(450, 370, 110, 20);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Menu");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 30, 190, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs_background/accountant-accounting-adviser-advisor-159804.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-340, -120, 1040, 630);

        setSize(new java.awt.Dimension(605, 449));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        JanelaPesquisarPrincipal jan = new JanelaPesquisarPrincipal();
        jan.setVisible(true);
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnGerenciarContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciarContasActionPerformed
        JanelaPrincipal gerenConta = new JanelaPrincipal(this.usuario);
        gerenConta.setVisible(true);
    }//GEN-LAST:event_btnGerenciarContasActionPerformed

    private void btnGerenciarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciarUsuariosActionPerformed
        JanelaPrincipalUsuarios  jan = new JanelaPrincipalUsuarios();
        jan.setVisible(true);
    }//GEN-LAST:event_btnGerenciarUsuariosActionPerformed

    private void btnGerenciarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciarClientesActionPerformed
        JanelaPrincipalClientes jan = new JanelaPrincipalClientes();
        jan.setVisible(true);
    }//GEN-LAST:event_btnGerenciarClientesActionPerformed

    private void btnEstatisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstatisticasActionPerformed
        // 
       // JanelaDeEstatisticas janEstats = new JanelaDeEstatisticas();
       // janEstats.setVisible(true);
        
    }//GEN-LAST:event_btnEstatisticasActionPerformed

    private void btnEstatisticasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstatisticasMouseClicked
        JPopupMenu menuPopUp = new JPopupMenu();
        JMenuItem itemContasPagar = new JMenuItem();
        JMenuItem itemContasReceber = new JMenuItem();
        itemContasPagar.setText("Contas a pagar");
        itemContasReceber.setText("Contas a receber");
        menuPopUp.add(itemContasPagar);
        menuPopUp.add(itemContasReceber);
        //menuPopUp.setBounds(evt.getX(), evt.getY(), 100, 100);
        //menuPopUp.setVisible(true);
        menuPopUp.show(btnEstatisticas,evt.getX(),evt.getY());
        
        itemContasPagar.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
               JanelaDeEstatisticas janEstats = new JanelaDeEstatisticas(usuario);
               janEstats.setVisible(true); 
            }
        });
        
        itemContasReceber.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                JanelaDeEstatisticasContasReceber janEstatsContaRecebeer = new JanelaDeEstatisticasContasReceber(usuario);
                janEstatsContaRecebeer.setVisible(true);
            }
        });
    }//GEN-LAST:event_btnEstatisticasMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstatisticas;
    private javax.swing.JButton btnGerenciarClientes;
    private javax.swing.JButton btnGerenciarContas;
    private javax.swing.JButton btnGerenciarUsuarios;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDataHora;
    // End of variables declaration//GEN-END:variables
}
