/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;
import classes.ContaReceber;
import classes.Cliente;
import classesDAO.ClienteDAO;
import classesDAO.ContaReceberDAO;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author bruno
 */
public class AlterarContaReceber extends javax.swing.JFrame {
private ContaReceber recebimentoAntigo;
    /**
     * Creates new form NovaContaReceber
     */
    public AlterarContaReceber(){
        initComponents();
          
        
    }
    
    public AlterarContaReceber(ContaReceber recebimentoAntigo){
        initComponents();
        this.recebimentoAntigo = recebimentoAntigo;
        
        this.txtCliente.enable(false);
        
       // colocando valores selecionados nos campos
        this.txtCliente.setText(recebimentoAntigo.getCliente());
        this.txtValorTotal1.setText(recebimentoAntigo.getValor() + "");
        this.numParcelas.setText(recebimentoAntigo.getParcela_total() + "");
        this.txtStatus.setText(recebimentoAntigo.getStatus());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtValorTotal1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        btnRegistrar1 = new javax.swing.JButton();
        numParcelas = new javax.swing.JTextField();
        txtDataVencimento1 = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/contract.png"))); // NOI18N
        jLabel1.setText("Alterar Conta a receber");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 20, 280, 90);

        jLabel2.setText("Cliente:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 130, 60, 20);

        jLabel3.setText("Valor total:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 190, 120, 30);

        jLabel4.setText("Parcelas:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(250, 190, 90, 30);
        getContentPane().add(txtValorTotal1);
        txtValorTotal1.setBounds(30, 220, 150, 27);

        jLabel5.setText("Data Vencimento:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 260, 130, 30);

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/correct-symbol.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(210, 370, 140, 40);

        btnRegistrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/remove-symbol.png"))); // NOI18N
        btnRegistrar1.setText("Cancelar");
        btnRegistrar1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar1);
        btnRegistrar1.setBounds(40, 370, 140, 40);
        getContentPane().add(numParcelas);
        numParcelas.setBounds(250, 220, 70, 27);

        txtDataVencimento1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        getContentPane().add(txtDataVencimento1);
        txtDataVencimento1.setBounds(30, 290, 150, 30);

        jLabel6.setText("Status:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 270, 70, 20);
        getContentPane().add(txtCliente);
        txtCliente.setBounds(30, 150, 150, 27);
        getContentPane().add(txtStatus);
        txtStatus.setBounds(200, 290, 130, 30);

        setSize(new java.awt.Dimension(404, 469));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegistrar1ActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        try{
            ContaReceber recebimento = new ContaReceber();                                   
            recebimento.setCod(this.recebimentoAntigo.getCod());
            recebimento.setValor(Double.parseDouble(this.txtValorTotal1.getText()));
            recebimento.setParcela_total(Integer.parseInt(this.numParcelas.getText()));
            recebimento.setStatus(this.txtStatus.getText());
            
           ContaReceberDAO.alterarRecebimento(recebimento);       
           
           JOptionPane.showMessageDialog(null, "Alterado com sucesso!");
           
           this.dispose();
          
        } catch (NumberFormatException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "erro: \n" + ex.getMessage());
        }    
    }//GEN-LAST:event_btnAlterarActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarContaReceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarContaReceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarContaReceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarContaReceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarContaReceber().setVisible(true);
            }
        });
    }

    public void setRecebimento(ContaReceber recebimento) {
        this.recebimentoAntigo = recebimento;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnRegistrar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField numParcelas;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JFormattedTextField txtDataVencimento1;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtValorTotal1;
    // End of variables declaration//GEN-END:variables
}
