/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janela_gerenciar_contas;
import classes.ContaReceber;
import classes.Cliente;
import classes.ContaPagar;
import classesDAO.ClienteDAO;
import classesDAO.ContaPagarDAO;
import classesDAO.ContaReceberDAO;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author bruno
 */
public class AlterarContaPagar extends javax.swing.JFrame {
private ContaPagar pagamentoAntigo;
JanelaPrincipal jan;
    /**
     * Creates new form NovaContaReceber
     */
    public AlterarContaPagar(){
        initComponents();        
    }
    
    public AlterarContaPagar(ContaPagar pagamentoAntigo){
        initComponents();
        carregarDados( pagamentoAntigo);
        
        
    }
    
      public AlterarContaPagar(ContaPagar recebimentoAntigo, JanelaPrincipal jan){
        initComponents();
        carregarDados( recebimentoAntigo);
        this.jan = jan;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        btnRegistrar1 = new javax.swing.JButton();
        numParcelas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taObs = new javax.swing.JTextArea();
        cbStatus = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtfDataVencimento = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##/##/####");
            this.txtfDataVencimento = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/contract.png"))); // NOI18N
        jLabel1.setText("Alterar Conta a Pagar");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 0, 190, 90);

        jLabel2.setText("Titulo:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 130, 60, 20);

        jLabel3.setText("Valor total:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 120, 120, 30);

        jLabel4.setText("Parcelas:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 200, 90, 30);
        getContentPane().add(txtValorTotal);
        txtValorTotal.setBounds(230, 150, 150, 20);

        jLabel5.setText("Data Vencimento:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 290, 130, 30);

        btnAlterar.setText("Alterar");
        btnAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(260, 510, 140, 40);

        btnRegistrar1.setText("Cancelar");
        btnRegistrar1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar1);
        btnRegistrar1.setBounds(40, 510, 140, 40);
        getContentPane().add(numParcelas);
        numParcelas.setBounds(30, 230, 70, 20);

        jLabel6.setText("Status:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(240, 290, 70, 30);
        getContentPane().add(txtTitulo);
        txtTitulo.setBounds(30, 150, 150, 20);

        taObs.setColumns(20);
        taObs.setRows(5);
        jScrollPane1.setViewportView(taObs);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 400, 330, 96);

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendente", "Confirmado ", "Cancelado", "Outro" }));
        getContentPane().add(cbStatus);
        cbStatus.setBounds(240, 320, 180, 30);

        jLabel8.setText("Obs:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 370, 70, 30);

        txtfDataVencimento.setToolTipText("Exemplo: 12/07/2017");
        getContentPane().add(txtfDataVencimento);
        txtfDataVencimento.setBounds(30, 320, 180, 30);

        setSize(new java.awt.Dimension(470, 613));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegistrar1ActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        try{
            ContaPagar pagamento = new ContaPagar();                                   
            pagamento.setCod(this.pagamentoAntigo.getCod());
            pagamento.setTitulo(this.txtTitulo.getText());
            pagamento.setValor(Double.parseDouble(this.txtValorTotal.getText()));
            pagamento.setParcela_total(Integer.parseInt(this.numParcelas.getText()));
            pagamento.setStatus(this.cbStatus.getItemAt(this.cbStatus.getSelectedIndex()));
            pagamento.setData_vencimento(this.txtfDataVencimento.getText());            
            pagamento.setObs( this.taObs.getText());
            
           ContaPagarDAO.alterarPagamento(pagamento);
           
           JOptionPane.showMessageDialog(null, "Alterado com sucesso!");
           
           //refresh tabela
          jan.refreshTablePagar(jan.getP_tabela());
          this.dispose();
          
        } catch (NumberFormatException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Preencha os campos corretamente");
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarContaPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarContaPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarContaPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarContaPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarContaPagar().setVisible(true);
            }
        });
    }

    public void setPagamento(ContaPagar pagamento) {
        this.pagamentoAntigo = pagamento;
    }
    
    public void carregarDados(ContaPagar pagamentoAntigo){
        this.pagamentoAntigo = pagamentoAntigo;       
        
       // colocando valores selecionados nos campos
        this.txtTitulo.setText(pagamentoAntigo.getTitulo());
        this.txtValorTotal.setText(pagamentoAntigo.getValor() + "");
        this.numParcelas.setText(pagamentoAntigo.getParcela_total() + "");        
        this.txtfDataVencimento.setText(pagamentoAntigo.getData_vencimento());
        this.taObs.setText(pagamentoAntigo.getObs());
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnRegistrar1;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numParcelas;
    private javax.swing.JTextArea taObs;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtValorTotal;
    private javax.swing.JTextField txtfDataVencimento;
    // End of variables declaration//GEN-END:variables
}
