package janela_gerenciar_contas;
//importando classes
import classes.*;
import classesDAO.ContaReceberDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bruno
 */
public class JanelaPrincipal extends javax.swing.JFrame {
    private  Usuario usuario;  
    
    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal(){        
        initComponents();            
    } 
    
    public JanelaPrincipal(Usuario usuario){        
        initComponents();
        this.usuario = usuario;
        modoJanela(this.usuario.getNivel_acesso());
        //funções conta a receber
        ContaReceber cr = new ContaReceber(); 
        cr.todosRecebimentosTabela(r_tabela);        
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    
    // modo como a janela vai abrir dependendo do nivel de acesso
    //do usuario
    public void modoJanela(int nivel_acesso){
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab_pane_principal = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        r_tabela = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        r_btn_pesquisa = new javax.swing.JButton();
        r_txt_pesquisa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        r_btn_registrar = new javax.swing.JButton();
        r_btn_alterar = new javax.swing.JButton();
        r_btn_excluir = new javax.swing.JButton();
        r_btn_confirmar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        p_tabela = new javax.swing.JTable();
        p_txt_pesquisa = new javax.swing.JTextField();
        p_btn_pesquisa = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        p_btn_registrar = new javax.swing.JButton();
        p_btn_alterar = new javax.swing.JButton();
        p_btn_excluir = new javax.swing.JButton();
        p_btn_confirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel4.setLayout(null);

        r_tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "código", "Cliente", "Valor", "Vencimento", "Parcelas", "modo pagamento", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(r_tabela);

        jPanel4.add(jScrollPane3);
        jScrollPane3.setBounds(10, 160, 940, 400);

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/contasReceber.png"))); // NOI18N
        jLabel7.setText("Gerenciar Contas a Receber");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(10, 90, 430, 80);

        r_btn_pesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/research.png"))); // NOI18N
        r_btn_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_btn_pesquisaActionPerformed(evt);
            }
        });
        jPanel4.add(r_btn_pesquisa);
        r_btn_pesquisa.setBounds(910, 130, 30, 30);
        jPanel4.add(r_txt_pesquisa);
        r_txt_pesquisa.setBounds(730, 130, 180, 30);

        jLabel9.setText("Pesquisar");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(730, 110, 140, 20);

        jToolBar1.setFloatable(false);

        r_btn_registrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        r_btn_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/file.png"))); // NOI18N
        r_btn_registrar.setText("Registrar");
        r_btn_registrar.setActionCommand("");
        r_btn_registrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        r_btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_btn_registrarActionPerformed(evt);
            }
        });
        jToolBar1.add(r_btn_registrar);

        r_btn_alterar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        r_btn_alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/contract.png"))); // NOI18N
        r_btn_alterar.setText("Alterar");
        r_btn_alterar.setToolTipText("Para alterar registros selecione a linha correspondente e clique no botão alterar");
        r_btn_alterar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        r_btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_btn_alterarActionPerformed(evt);
            }
        });
        jToolBar1.add(r_btn_alterar);

        r_btn_excluir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        r_btn_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/trash.png"))); // NOI18N
        r_btn_excluir.setText("Excluir");
        r_btn_excluir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        r_btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_btn_excluirActionPerformed(evt);
            }
        });
        jToolBar1.add(r_btn_excluir);

        r_btn_confirmar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        r_btn_confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/deal.png"))); // NOI18N
        r_btn_confirmar.setText("Confirmar");
        r_btn_confirmar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        r_btn_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_btn_confirmarActionPerformed(evt);
            }
        });
        jToolBar1.add(r_btn_confirmar);

        jPanel4.add(jToolBar1);
        jToolBar1.setBounds(2, 2, 970, 60);

        tab_pane_principal.addTab("Contas a Receber", jPanel4);

        jPanel6.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/contasReceber.png"))); // NOI18N
        jLabel8.setText("Gerenciar Contas a Pagar");
        jPanel6.add(jLabel8);
        jLabel8.setBounds(10, 90, 430, 80);

        p_tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "código", "Titulo", "Valor", "Vencimento", "Parcelas", "modo pagamento", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(p_tabela);

        jPanel6.add(jScrollPane4);
        jScrollPane4.setBounds(10, 160, 940, 400);
        jPanel6.add(p_txt_pesquisa);
        p_txt_pesquisa.setBounds(730, 130, 180, 30);

        p_btn_pesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/research.png"))); // NOI18N
        p_btn_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_btn_pesquisaActionPerformed(evt);
            }
        });
        jPanel6.add(p_btn_pesquisa);
        p_btn_pesquisa.setBounds(910, 130, 30, 30);

        jLabel10.setText("Pesquisar");
        jPanel6.add(jLabel10);
        jLabel10.setBounds(730, 110, 140, 20);

        jToolBar2.setFloatable(false);

        p_btn_registrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        p_btn_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/file.png"))); // NOI18N
        p_btn_registrar.setText("Registrar");
        p_btn_registrar.setActionCommand("");
        p_btn_registrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        p_btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_btn_registrarActionPerformed(evt);
            }
        });
        jToolBar2.add(p_btn_registrar);

        p_btn_alterar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        p_btn_alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/contract.png"))); // NOI18N
        p_btn_alterar.setText("Alterar");
        p_btn_alterar.setToolTipText("Para alterar registros selecione a linha correspondente e clique no botão alterar");
        p_btn_alterar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        p_btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_btn_alterarActionPerformed(evt);
            }
        });
        jToolBar2.add(p_btn_alterar);

        p_btn_excluir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        p_btn_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/trash.png"))); // NOI18N
        p_btn_excluir.setText("Excluir");
        p_btn_excluir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        p_btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_btn_excluirActionPerformed(evt);
            }
        });
        jToolBar2.add(p_btn_excluir);

        p_btn_confirmar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        p_btn_confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/deal.png"))); // NOI18N
        p_btn_confirmar.setText("Confirmar");
        p_btn_confirmar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        p_btn_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_btn_confirmarActionPerformed(evt);
            }
        });
        jToolBar2.add(p_btn_confirmar);

        jPanel6.add(jToolBar2);
        jToolBar2.setBounds(2, 2, 970, 60);

        tab_pane_principal.addTab("Contas a Pagar", jPanel6);

        getContentPane().add(tab_pane_principal);
        tab_pane_principal.setBounds(0, 0, 970, 630);

        setSize(new java.awt.Dimension(980, 663));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void r_btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_btn_excluirActionPerformed
        int linhaSelecionada = this.r_tabela.getSelectedRow();
        if(linhaSelecionada >  -1){
            int resp = JOptionPane.showConfirmDialog(null, "Excluir Recebimento ?");
            if(resp == 0){
                int id = Integer.parseInt(this.r_tabela.getValueAt(linhaSelecionada, 0).toString());

                try {
                    ContaReceberDAO.excluirRecebimento(id);
                    JOptionPane.showMessageDialog(null, "Deletado com sucesso!");
                     refreshTable(this.r_tabela);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Erro ao excluir!");
                }
            }
        }else {
            JOptionPane.showMessageDialog(null, "Escolha um registro para excluir !");
        }
    }//GEN-LAST:event_r_btn_excluirActionPerformed

    private void r_btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_btn_alterarActionPerformed
        int linhaSelecionada = this.r_tabela.getSelectedRow();
        if(linhaSelecionada >  -1){
            ContaReceber recebimento = new ContaReceber();
            recebimento.setCod(Integer.parseInt(this.r_tabela.getValueAt(linhaSelecionada , 0).toString()));
            recebimento.setCliente(this.r_tabela.getValueAt(linhaSelecionada , 1).toString());
            recebimento.setValor(Double.parseDouble(this.r_tabela.getValueAt(linhaSelecionada , 2).toString()));
            recebimento.setParcela_total(Integer.parseInt(this.r_tabela.getValueAt(linhaSelecionada , 4).toString()));     
            recebimento.setModo_pagamento(this.r_tabela.getValueAt(linhaSelecionada , 5).toString());
            recebimento.setStatus(this.r_tabela.getValueAt(linhaSelecionada , 6).toString());
            
            AlterarContaReceber jan = new AlterarContaReceber(recebimento, this);
            jan.show();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um registro para alterar!");
        }
    }//GEN-LAST:event_r_btn_alterarActionPerformed

    private void r_btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_btn_registrarActionPerformed
        NovaContaReceber jan = new NovaContaReceber(this);
        jan.show();
    }//GEN-LAST:event_r_btn_registrarActionPerformed

    private void r_btn_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_btn_pesquisaActionPerformed
       ContaReceber conta = new ContaReceber();
       conta.pesquisarTabela(this.r_tabela, this.r_txt_pesquisa.getText());
    }//GEN-LAST:event_r_btn_pesquisaActionPerformed

    //---CONFIRMAR RECEBIMENTO
    private void r_btn_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_btn_confirmarActionPerformed
         int linhaSelecionada = this.r_tabela.getSelectedRow();
        if(linhaSelecionada >  -1){
            int resp = JOptionPane.showConfirmDialog(null, "Confirmar Recebimento ?");
            if(resp == 0){
                int id = Integer.parseInt(this.r_tabela.getValueAt(linhaSelecionada, 0).toString());

                try {
                    ContaReceberDAO.confirmarRecebimento(id);
                    JOptionPane.showMessageDialog(null, "Confirmado com sucesso!");
                     refreshTable(this.r_tabela);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Erro ao Confirmar!");
                }
            }
        }else {
            JOptionPane.showMessageDialog(null, "Selecione um registro para Confirmar !");
        }
    }//GEN-LAST:event_r_btn_confirmarActionPerformed

    private void p_btn_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_btn_pesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_btn_pesquisaActionPerformed

    private void p_btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_btn_registrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_btn_registrarActionPerformed

    private void p_btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_btn_alterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_btn_alterarActionPerformed

    private void p_btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_btn_excluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_btn_excluirActionPerformed

    private void p_btn_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_btn_confirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_btn_confirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {              
              new JanelaPrincipal().setVisible(true);             
            }
        });
    }
    
    public void refreshTable(JTable table ){
        ContaReceber conta = new ContaReceber();
        conta.todosRecebimentosTabela(table);
    }

    public JTable getP_tabela() {
        return p_tabela;
    }

    public JTable getR_tabela() {
        return r_tabela;
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JButton p_btn_alterar;
    private javax.swing.JButton p_btn_confirmar;
    private javax.swing.JButton p_btn_excluir;
    private javax.swing.JButton p_btn_pesquisa;
    private javax.swing.JButton p_btn_registrar;
    private javax.swing.JTable p_tabela;
    private javax.swing.JTextField p_txt_pesquisa;
    private javax.swing.JButton r_btn_alterar;
    private javax.swing.JButton r_btn_confirmar;
    private javax.swing.JButton r_btn_excluir;
    private javax.swing.JButton r_btn_pesquisa;
    private javax.swing.JButton r_btn_registrar;
    private javax.swing.JTable r_tabela;
    private javax.swing.JTextField r_txt_pesquisa;
    private javax.swing.JTabbedPane tab_pane_principal;
    // End of variables declaration//GEN-END:variables
}
